### ISSUE TITLE
error output in el7: "FirewallD is not running"

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-linux-formula#205]
Happens when running tests via travis-ci within the centos7 docker container. Appears to be generated by RHEL-07-040250, when running: 

```
{%- set fwRule = salt.cmd.shell('firewall-cmd --direct --get-rule ipv4 filter IN_public_allow') %}
```

Not sure the impact is significant, but seems likely the state is not running as one might expect in the test.

**Comment by ferricoxide** [comment]
Was the `--privileged` flag set on the container when this error was encountered?

The firewalld and iptables interfaces use kernel-level controls. If you issue a firewalld/iptables command within docker, due to the shared-kernel structure of docker, those actions effect the hosting-node's iptables/firewalld configuration. The `--privileged` flag _should_ allow that to occur ...but may have other impacts. Similarly, other things — like the [capabilities security subsystem](http://man7.org/linux/man-pages/man7/capabilities.7.html) — could be blocking its use. 

My recollection is that, in addition to setting `--privileged`, for firewalld to work within a container the hosting-node needs to also have firewalld installed/loaded/running and its interfaces exposed to the container (and then firewalld installed/loaded/running in the container). It used to be a righteous pain-in-the dick to sort out. Maybe it's gotten better, though.

With respect to prior mention of capabilities: I've no clue what travis CI's security posture is. However, one would think they might hamstring the use of iptables/firewalld within containers to prevent a test from knocking a node off the air or otherwise junking things up for other test-containers on the same node (see [Docker Capabilities note](https://docs.docker.com/engine/security/security/#/linux-kernel-capabilities)).

/shrug

**Comment by ferricoxide** [comment]
In doing the automation for the DOTC projects, ran into this issue, again. In current versions of EL7 (mebbe 7.4 will fix things), this happens when SELinux is enabled and `firewall-cmd` is run outside of an expected SEL context (use of init-owned automation processes like `cloud-init` will trigger it). A work-around to the problem is to do `setenforce 0 && firwallcmd ... && setenforce 1`
