### ISSUE TITLE
error output in el6: "No matching Packages to list"

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-linux-formula#206]
Appears to be resulting from cat1.V38666 due to this jinja call: `{%- if salt.pkg.latest_version(MSFEpkg) %}`.

Can duplicate the message from the cli by executing:

```
# salt-call --local pkg.latest_version MSFEpkg
[ERROR   ] Problem encountered getting latest version for the following package(s): MSFEpkg. Stderr follows:
Error: No matching Packages to list
```

**Comment by ferricoxide** [comment]
That would fall under "expected behavior".

**Comment by lorengordon** [comment]
I don't think we should "expect" to see any errors when applying any states. To me, it indicates a problem with the logic or the selected mechanism for the check.

**Comment by ferricoxide** [comment]
- If deploying to an environment known to support McAfee via RPM-repo, it's appropriate to activate the method and for it to exit-fail if it's unable to talk to the repo.
- If deploying to an environment known to _not_ support McAfee via RPM-repo, then it's not appropriate to activate the method.

Two choices on remediating the issue:
- Implicit: (McAfee _needs_ to come from somewhere if the formula is being selected for run) if there's a Pillar-item pointing to a download, assume that's the only valid repository and skip the RPM-check; otherwise run it 
- Explicit: check for a repo-check Pillar-item; run/skip based on that pillar

Either way: if running in an environment known to have no EPO support, the formula should not be auto-included in the provisioning framework. Including *all* layers in a run, even when you know that they're not appropriate to the environment, kind of negates a modular design (if you're always running everything everywhere, may as well just have one, monolithic formula and call it a day).

**Comment by lorengordon** [comment]
The error is coming from the rendering stage. Rendering shouldn't generate errors. The test is an attempt to perform the second option: check if the package is available, and run/skip based on the result. Except the test itself generates this spurious error output. Since we are explicitly handling the error condition, it is not an error that should be output.

**Comment by ferricoxide** [comment]
Proposed-surgery:
- Excise [chunk](https://github.com/plus3it/ash-linux-formula/blob/master/ash-linux/el6/STIGbyID/cat1/V38666.sls#L48-L62).
- While we're in there, make [this guy](https://github.com/plus3it/ash-linux-formula/blob/master/ash-linux/el6/STIGbyID/cat1/V38666.sls#L64-L68) stateful

Future enhancement: find a way to compare any installed version to what might be in relevant buckets (via pillar-data)

**Comment by ferricoxide** [comment]
OBE: EL6 no longer supported by vendor
