### ISSUE TITLE
Nessus scans reporting on weak MACs and CBC ciphers used by sshd

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-linux-formula#214]
Potential fix appears to be https://access.redhat.com/solutions/420283

**Comment by ferricoxide** [comment]
EL6 or EL7?

* If EL6, the Ciphers are addressed in cat2/V38617 — at least as the STIG-specified list existed when the module was written
* If EL7, this would be a "dumb scanner" issue: enablement of FIPS mode means that non-compliant encryptions methods are disabled at the kernel and specification within the `sshd_config` is redundant.

**Comment by lorengordon** [comment]
EL6

Though I expect it is a dumb scanner and we'd end up having to address the finding somehow on EL7 in FIPS-mode also (either by modifying sshd_config or having the same "it's not an applicable finding" conversation over and over and over).

**Comment by ferricoxide** [comment]
Ok. Forking/cloning, now. I'll pull the lasted EL6 STIG to see what the "as of today" list is.

EL7 will be a skosh trickier since we're (now) wholly-reliant on what `oscap` automated-remediation implements. That said, as long as the system's patched-up (and we continue to use the vendor-STIG content), `oscap` should always just Do The Right Thing&trade;.

**Comment by ferricoxide** [comment]
Nice: the current STIG doesn't even include that STIG ID and there isn't a STIG ID that _does_ reference the allowable Ciphers. A search using the STIG viewer doesn't have hits for CIPHER, at all. And all of the `sshd_config` hits reference other config items. Is their Nessus scanner using the January STIG contents for EL6???

**Comment by lorengordon** [comment]
I don't think the Nessus scan was based on the stig at all. I usually put fixes for Nessus scan findings under a different baseline (not the stig).

**Comment by ferricoxide** [comment]
Greh... Was going to push a changed from existing STIG handler. If I move to a "Nessus"/"custom" (or similar) folder, I'll need to nuke the STIG file (probably fine, since it's no longer a valid Vuln-ID, any way) so we don't have two things attempting to set the ciphers/macs. Need to also modify the relevant `init.sls` files.

Leave in the existing STIG-handler or move?
